command_timeout = 500 # 1010 if you enable git_status

[python]
symbol = '󰌠 '

# [git_status]
# disabled = true

[rlang]
symbol = '  '

[rust]
symbol = ' '

[lua]
symbol = '󰢱 '

[java]
symbol = '󰬷 '
